### ISSUE TITLE
APPVEYOR_PROJECT_NAME is not the same as Julia project name

### ISSUE THREAD

**Issue by isuruf** [simonbyrne/Appveyor.jl#10]
In my appveyor account, I have the project from an org and my personal fork both activated. I change the org project name to `symengine/SymEngine.jl` instead of just `SymEngine.jl` to figure out if it's the fork or not. Unfortunately this breaks the script. Is there a way to get the project name from elsewhere?

**Comment by simonbyrne** [comment]
I don't quite understand: can you point to the repo and appveyor trace?

**Comment by isuruf** [comment]
Here's the appveyor log https://ci.appveyor.com/project/isuruf/symengine-jl-pj80f/build/1.0.149/job/m87te0srql9n7gl9

Here's the workaround I used https://github.com/symengine/SymEngine.jl/commit/c6ff8f479702b33cd978be1ac7f19be337f97732
