### ISSUE TITLE
How to add dependencies 

### ISSUE THREAD

**Issue by yakir12** [simonbyrne/Appveyor.jl#15]
What if my tests depend on `ffmpeg`? In Travis I can:
```yml
before_install:
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./test/install_ffmpeg.sh ; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install ffmpeg; fi
```
where `./test/install_ffmpeg.sh` is a bunch of `sudo apt-get install`s.

**Comment by simonbyrne** [comment]
just add extra lines to the `install` block, e.g. https://github.com/JuliaInterop/RCall.jl/blob/master/appveyor.yml

**Comment by yakir12** [comment]
Testing, also saw [this](https://www.appveyor.com/docs/build-configuration/#installing-additional-software) and hoping this will simply work:
```yml
  - cinst ffmpeg
```

**Comment by yakir12** [comment]
It worked! Thanks.
