### ISSUE TITLE
1 doesn't test latest release

### ISSUE THREAD

**Issue by Datseris** [simonbyrne/Appveyor.jl#17]
Even though I use `1` in my copied appveyor file:
```
environment:
  matrix:
  - julia_version: 1
```

the Julia version used is not the latest stable release. proof: https://ci.appveyor.com/project/JuliaDynamics/recurrenceanalysis-jl/branch/master/job/83t944m9f9ipo2ae 

Do I simply have to be more patient because this process takes time, or is there something wrong?

**Comment by simonbyrne** [comment]
Fixed by e4f3333bfbded094ec27c4a80beafbe29470e41a. Should now be working.
