### ISSUE TITLE
Can't test unnamed project

### ISSUE THREAD

**Issue by fredrikekre** [simonbyrne/Appveyor.jl#5]
I just got this failure: https://ci.appveyor.com/project/fredrikekre/literate-jl/build/1.0.80 which supposedly should have been fixed by c379d6d2dd7eb2c7adad60939e3026a59ef32caa but that does not seem to be the correct solution.

**Comment by fredrikekre** [comment]
Is the problem that we never `cd` to the clone?

**Comment by simonbyrne** [comment]
That was my fault: I forked the `version-1` branch without first pulling in the latest `master`. Fixed by 2021358433dee87e58a7ade390aa2fa228397383

**Comment by simonbyrne** [comment]
(this should now work if you restart the build)

**Comment by fredrikekre** [comment]
Yep already did, thanks!
