### ISSUE TITLE
Error when using rm() in AppVeyor

### ISSUE THREAD

**Issue by diegozea** [simonbyrne/Appveyor.jl#6]
Hi, I have a code that deletes a temporal testing file using `rm(...)` that gives the following error in AppVeyor:

https://ci.appveyor.com/project/diegozea/mitos-jl/branch/master/job/aygs2bu6qr4cdska#L5014

Do you know how this can be solved?

Thanks in advance,

**Comment by simonbyrne** [comment]
That's usually because the OS still thinks the file is being accessed, see https://discourse.julialang.org/t/windows-specific-uv-error/3127

**Comment by simonbyrne** [comment]
(it's a general Windows thing, not an Appveyor issue)
